name: Build Custom Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build_db:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DB_ID: bios_db

    steps:    
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils

    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v2
    - name: Build Custom Database for MiSTer Downloader
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py | python3 -

    - name: Add NeoGeo UniBios
      run: |
        if [ ! -f db.json ]; then
          curl --fail --location --output "${RUNNER_TEMP}/db.json.zip" \
            https://raw.githubusercontent.com/ajgowans/BiosDB_MiSTer/refs/heads/db/db.json.zip
          echo "7b1674fe38fa73c429ecc9318a24d548  ${RUNNER_TEMP}/db.json.zip" | md5sum --check --status || exit 0

          cp .github/add_neogeo_unibios.py "${RUNNER_TEMP}/"
          git fetch origin db
          git checkout -B db FETCH_HEAD
          unzip -q "${RUNNER_TEMP}/db.json.zip"
          touch db.json
          zip -q -f db.json.zip db.json

          python3 "${RUNNER_TEMP}/add_neogeo_unibios.py"
          git add db.json.zip bios_db.json bios_db.json.zip
          git commit -m "Creating bios_db DB"
          git push origin db
          exit 0
        fi

        python3 .github/add_neogeo_unibios.py
        git add bios_db.json bios_db.json.zip
        git commit -m "Creating bios_db DB"
        git push origin db
